# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1' 

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze lib/templates/lab8/

      - name: Run tests
        run: flutter test test/wid_test.dart

      - name: Build
        run: flutter build web --target=lib/templates/lab8/main.dart

      - name: pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
